### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by antonioreyna** [northwoodspd/FluentConstraints#1]
can you upgrade it to swift 3? thanks

**Comment by msullivan247** [comment]
We've updated to Swift 3.0, and are ready to push a new version of the pod, I'm just waiting for the original author to give me co-ownership of the pod to do so.

In the meantime, you can point to master in your podfile, and you should be able to proceed.

**Comment by msullivan247** [comment]
Version 2.0 has been pushed to CocoaPods.org. Thanks for reminding us to update!
